sonar.projectKey=vermaldonado-ia_intelligent-logistics-control-platform
sonar.organization=vermaldonado-ia

sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
